force-app/main/default/objects/ERPIntegrationSettings__mdt/ERPIntegrationSettings__mdt.object-meta.xml
<CustomObject>
    <description>JJDSF-329</description>
    <label>ERPIntegrationSetting</label>
    <pluralLabel>ERP Integration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ERPIntegrationSettings__mdt/fields/EndpointPath__c.field-meta.xml
<CustomField>
    <fullName>EndpointPath__c</fullName>
    <label>Endpoint Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorLogging__c/ErrorLogging__c.object-meta.xml
<CustomObject>
    <description>Captures all errors of scheduled jobs.</description>
    <label>Error Logging</label>
    <nameField>
        <displayFormat>ERROR-{0000000}</displayFormat>
        <label>Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Loggings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLogging__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <description>The Error Body.</description>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorLogging__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <description>The name of the process which triggered the error.</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderSimulationController.cls
public with sharing class OrderSimulationController {
    public static ReturnWrapper sendToOrderSimulation(String body, ERPIntegrationSettings__mdt cfg) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint(('callout:ERP_API_NEW') + (cfg.EndpointPath__c ?? ''));
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(body);

        Http http = new Http();
        HttpResponse res = http.send(req);

        if(res.getStatusCode() >= 300){
            Map<String, Object> data = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            String errorMessage = data.containsKey('error') ? (String)data.get('error') : 'Unknown Error';
            ErrorLogging__c el = new ErrorLogging__c(
                ProcessName__c = 'Order Simulation',
                Error__c = errorMessage
            );
            insert el;
            return new ReturnWrapper(false, el.Id, errorMessage, null);
        }
        
        Map<String, Object> data = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
        return new ReturnWrapper(true, null, null, data);
    }

    public class ReturnWrapper{
        @AuraEnabled public Boolean isSuccess;
        @AuraEnabled public String errorLogId;
        @AuraEnabled public String errorMessage;
        @AuraEnabled public Map<String, Object> data;
        public ReturnWrapper(Boolean isSuccess, String errorLogId, String errorMessage, Map<String, Object> data){
            this.isSuccess = isSuccess;
            this.errorLogId = errorLogId;
            this.errorMessage = errorMessage;
            this.data = data;
        }
    }
}