force-app/main/default/objects/WebshopProductLink__c/WebshopProductLink__c.object-meta.xml
<CustomObject>
    <description>Product Links for the LWR webshop.</description>
    <label>Webshop Product Link</label>
    <nameField>
        <displayFormat>LINK-{0000000}</displayFormat>
        <label>Webshop Product Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webshop Product Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WebshopProductLink__c/fields/Product1__c.field-meta.xml
<CustomField>
    <fullName>Product1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>WebshopProductLinksOne</relationshipLabel>
    <relationshipName>WebshopProductLinksOne</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WebshopProductLink__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>WebshopProductLinksTwo</relationshipLabel>
    <relationshipName>WebshopProductLinksTwo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WebshopProductLink__c/fields/UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>UniqueIdentifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/WebshopProductLinkTriggerHandler.cls
public with sharing class WebshopProductLinkTriggerHandler {
    public static void validateDuplicates(List<WebshopProductLink__c> newRecords){
        for(WebshopProductLink__c newRecord : newRecords){
            List<String> sortedLinks = new List<String>{newRecord.Product1__c, newRecord.Product2__c};
            sortedLinks.sort();
            newRecord.UniqueIdentifier__c = String.join(sortedLinks, '');
        }
    }
}