force-app/main/default/objects/CartItem/fields/CartFreeItem__c.field-meta.xml
<CustomField>
    <fullName>CartFreeItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CRM-1564</description>
    <label>Cart Free Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CartItem/fields/FreeItem__c.field-meta.xml
<CustomField>
    <fullName>FreeItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CRM-580 Checked if row has been auto created by CartItemTrigger.</description>
    <label>Free Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CartItem/fields/LetterCampaignFreeItem__c.field-meta.xml
<CustomField>
    <fullName>LetterCampaignFreeItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CRM-553</description>
    <label>Letter Campaign Free Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CartItem/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <formula>Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebCart/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CartItemTriggerHandler.cls
public without sharing class CartItemTriggerHandler {
    @TestVisible
    private static final List<String> SHIPPING_PRODUCT_CODES = System.Label.ShippingProductCodes.split(',');
    public static Boolean hasTriggerRan = false;

    public static void triggerCarts(List<CartItem> newRecords){
        Boolean run = false;
        for(CartItem ci : newRecords){
            if(!ci.LetterCampaignFreeItem__c && !ci.FreeItem__c && !ci.CartFreeItem__c){
                run = true;
            }
        }
        // Only run if we have neither free items nor letter campaign free items
        if(run){
            List<String> allCartIds = new List<String>();
            for(CartItem ci : newRecords){
                if(!ci.FreeItem__c && !ci.LetterCampaignFreeItem__c && !SHIPPING_PRODUCT_CODES.contains(ci.ProductCode__c)){
                    allCartIds.add(ci.CartId);
                }
            }
            if(!allCartIds.isEmpty()){
                List<WebCart> carts = [SELECT Id, AccountId, WebStoreId, (SELECT Id, CartDeliveryGroupId FROM CartItems WHERE FreeItem__c = FALSE AND CartFreeItem__c = FALSE AND LetterCampaignFreeItem__c = FALSE) FROM WebCart WHERE Id IN : allCartIds];

                Map<Id, CartItem> hasCartFreeItems = new Map<Id, CartItem>();
                for(CartItem ci : [SELECT Id, CartId FROM CartItem WHERE CartId IN : carts AND CartFreeItem__c = TRUE]){
                    hasCartFreeItems.put(ci.CartId, ci);
                }

                Map<Id, Decimal> sumMap = new Map<Id, Decimal>();
                for(AggregateResult ar : [SELECT SUM(TotalLineAmount) sumVal, CartId FROM CartItem WHERE Product2.ProductCode NOT IN :SHIPPING_PRODUCT_CODES AND CartId IN : allCartIDs GROUP BY CartId]){
                    sumMap.put(String.valueOf(ar.get('CartId')), (Decimal)ar.get('sumVal'));
                }
                List<CartItem> cartItemsToDelete = new List<CartItem>();
                for(WebCart cart : carts){
                    cart.TotalAmount__c = sumMap.containsKey(cart.Id) ? sumMap.get(cart.Id) : 0;
                    if(hasCartFreeItems.containsKey(cart.Id)){
                        cartItemsToDelete.add(hasCartFreeItems.get(cart.Id));
                    }

                }
                if(!cartItemsToDelete.isEmpty()){
                    delete cartItemsToDelete;
                }
                WebCartTriggerHandler.checkLetterCampaignFreeItemsAndShippingCosts(carts);
            }
        }
    }

    public static void checkTriggerRun(List<CartItem> newRecords){
        Boolean run = false;
        for(CartItem ci : newRecords){
            if(!ci.LetterCampaignFreeItem__c && !ci.FreeItem__c && !ci.CartFreeItem__c){
                hasTriggerRan = true;
            }
        }
    }
}