force-app/main/default/objects/ManagedContent__c/ManagedContent__c.object-meta.xml
<CustomObject>
    <label>Managed Content</label>
    <nameField>
        <displayFormat>MC-{0000000}</displayFormat>
        <label>Managed Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ManagedContent__c/fields/ContentKey__c.field-meta.xml
<CustomField>
    <fullName>ContentKey__c</fullName>
    <label>Content Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ManagedContent__c/fields/ManagedContentID__c.field-meta.xml
<CustomField>
    <fullName>ManagedContentID__c</fullName>
    <externalId>true</externalId>
    <label>Managed Content ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/WebshopScheduledCopyManagedContent.cls
/*
* Created by: Stanley Yin
* Created Date: 06.11.2024
*/

public without sharing class WebshopScheduledCopyManagedContent implements Schedulable, Database.Batchable<sObject>, Database.Stateful {
    public Boolean allContent {get; set;}
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new WebshopScheduledCopyManagedContent(false), 100);
    }
    public WebshopScheduledCopyManagedContent(){
        this.allContent = false;
    }
    public WebshopScheduledCopyManagedContent(Boolean allContent){
        this.allContent = allContent;
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        DateTime dt = System.Now().addDays(-2);
        return Test.isRunningTest() ? 
            Database.getQueryLocator('SELECT Id, ContentKey FROM ManagedContent ORDER BY CreatedDate DESC LIMIT 1') : 
            !this.allContent ? Database.getQueryLocator('SELECT Id, ContentKey FROM ManagedContent WHERE LastModifiedDate >= :dt') : Database.getQueryLocator('SELECT Id, ContentKey FROM ManagedContent');
    }
    
    public void execute(Database.BatchableContext bc, List<ManagedContent> scope) {
        List<ManagedContent__c> newRecords = new List<ManagedContent__c>();
        for(ManagedContent mc : scope){
            newRecords.add(new ManagedContent__c(
                ManagedContentId__c = mc.Id,
                ContentKey__c = mc.ContentKey
            ));
        }
        upsert newRecords ManagedContentId__c;
    }

    public void finish(Database.BatchableContext bc){ /* Do nothing */ }
}