force-app/main/default/objects/ErrorLogging__c/ErrorLogging__c.object-meta.xml
<CustomObject>
    <description>Captures all errors of scheduled jobs.</description>
    <label>Error Logging</label>
    <nameField>
        <displayFormat>ERROR-{0000000}</displayFormat>
        <label>Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Loggings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/BoxCount__c.field-meta.xml
<CustomField>
    <fullName>BoxCount__c</fullName>
    <label>Box Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Factor__c.field-meta.xml
<CustomField>
    <fullName>Factor__c</fullName>
    <label>Factor</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PaletteCount__c.field-meta.xml
<CustomField>
    <fullName>PaletteCount__c</fullName>
    <label>Palette Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductAttribute/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ST</fullName>
                <label>Stück</label>
            </value>
            <value>
                <fullName>KAR</fullName>
                <label>Karton</label>
            </value>
            <value>
                <fullName>PAL</fullName>
                <label>Palette</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>Gramm</label>
            </value>
            <value>
                <fullName>LAG</fullName>
                <label>Lagen pro Palette</label>
            </value>
            <value>
                <fullName>SP</fullName>
                <label>Stellplatz</label>
            </value>
            <value>
                <fullName>KG</fullName>
                <label>Kilogramm</label>
            </value>
            <value>
                <fullName>ROL</fullName>
                <label>Rolle</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>Meter</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>Länge in Metern pro Einheit</label>
            </value>
            <value>
                <fullName>COP</fullName>
                <label>Kopien</label>
            </value>
            <value>
                <fullName>DEG</fullName>
                <label>Grad</label>
            </value>
            <value>
                <fullName>DGP</fullName>
                <label>ADR GG-Freistellungspunkte</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Dutzend</label>
            </value>
            <value>
                <fullName>EA</fullName>
                <label>Stück (EA)</label>
            </value>
            <value>
                <fullName>EE</fullName>
                <label>Einheiten Enzyme</label>
            </value>
            <value>
                <fullName>EML</fullName>
                <label>Einheiten Enzyme / Milliliter</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>Flasche</label>
            </value>
            <value>
                <fullName>G/L</fullName>
                <label>Gramm Wirkstoff / Liter</label>
            </value>
            <value>
                <fullName>GAU</fullName>
                <label>Gramm Gold</label>
            </value>
            <value>
                <fullName>GKM</fullName>
                <label>Gramm/Kilometer</label>
            </value>
            <value>
                <fullName>GRO</fullName>
                <label>Gross</label>
            </value>
            <value>
                <fullName>GW</fullName>
                <label>Gramm Wirkstoff</label>
            </value>
            <value>
                <fullName>KAN</fullName>
                <label>Kanister</label>
            </value>
            <value>
                <fullName>KGW</fullName>
                <label>Kilogramm Wirkstoff</label>
            </value>
            <value>
                <fullName>KI</fullName>
                <label>Kiste</label>
            </value>
            <value>
                <fullName>KS</fullName>
                <label>Kasten</label>
            </value>
            <value>
                <fullName>KWK</fullName>
                <label>kg Wirkstoff / kg</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <label>Liter Alkohol</label>
            </value>
            <value>
                <fullName>LE</fullName>
                <label>Leistungseinheit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DailyCalculateMaxBatchPaletteCount.cls
/*
* Created by: Stanley Yin
* Created Date: 05-11-2025
* Purpose: Batch Job to calculate BoxCount__c and PaletteCount__c
*/

public without sharing class DailyCalculateMaxBatchPaletteCount implements Schedulable, Database.Batchable<sObject> {
    // Start method: Retrieve Custom ErrorLogging__c records
    public static void execute(SchedulableContext sc) {
        Database.executeBatch(new DailyCalculateMaxBatchPaletteCount(), 100);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id FROM Product2 WHERE IsActive = TRUE AND ProductClass = 'VariationParent']);
    }
    
    public void execute(Database.BatchableContext bc, List<Product2> scope){
        Map<Id, Product2> productsToUpdate = new Map<Id, Product2>();
        Map<Id, List<Product2>> parentToPieceMap = new Map<Id, List<Product2>>();
        Map<Id, List<Product2>> parentToBoxMap = new Map<Id, List<Product2>>();
        Map<Id, Map<String, Integer>> perUnitMap = new Map<Id, Map<String, Integer>>();
        for(ProductAttribute att : [SELECT Unit__c, ProductId, Product.Factor__c, VariantParentId FROM ProductAttribute WHERE VariantParentId IN :scope]){
            if(att.Unit__c == 'STUECK'){
                List<Product2> innerList = parentToPieceMap.containsKey(att.VariantParentId) ? parentToPieceMap.get(att.VariantParentId) : new List<Product2>();
                innerList.add(att.Product);
                parentToPieceMap.put(att.VariantParentId, innerList);
            } else if(att.Unit__c == 'KARTON'){
                List<Product2> innerList = parentToBoxMap.containsKey(att.VariantParentId) ? parentToBoxMap.get(att.VariantParentId) : new List<Product2>();
                innerList.add(att.Product);
                parentToBoxMap.put(att.VariantParentId, innerList);
                if(att.Product.Factor__c != null){
                    Map<String, Integer> innerMap = perUnitMap.containsKey(att.VariantParentId) ? perUnitMap.get(att.VariantParentId) : new Map<String, Integer>();
                    innerMap.put('box', Integer.valueOf(att.Product.Factor__c));
                    perUnitMap.put(att.VariantParentId, innerMap);
                }
            } else if(att.Unit__c == 'PALETTE'){
                if(att.Product.Factor__c != null){
                    Map<String, Integer> innerMap = perUnitMap.containsKey(att.VariantParentId) ? perUnitMap.get(att.VariantParentId) : new Map<String, Integer>();
                    innerMap.put('palette', Integer.valueOf(att.Product.Factor__c));
                    perUnitMap.put(att.VariantParentId, innerMap);
                }
            }
        }
        for(Id variationParentId : parentToPieceMap.keySet()){
            for(Product2 prodToUpdate : parentToPieceMap.get(variationParentId)){
                prodToUpdate.BoxCount__c = perUnitMap.containsKey(variationParentId) && perUnitMap.get(variationParentId).containsKey('box') ? perUnitMap.get(variationParentId).get('box') : null;
                prodToUpdate.PaletteCount__c = perUnitMap.containsKey(variationParentId) && perUnitMap.get(variationParentId).containsKey('palette') ? perUnitMap.get(variationParentId).get('palette') : null;
                productsToUpdate.put(prodToUpdate.Id, prodToUpdate);
            }
        }
        for(Id variationParentId : parentToBoxMap.keySet()){
            for(Product2 prodToUpdate : parentToBoxMap.get(variationParentId)){
                prodToUpdate.BoxCount__c = null;
                prodToUpdate.PaletteCount__c = prodToUpdate.Factor__c != null && perUnitMap.containsKey(variationParentId) && perUnitMap.get(variationParentId).containsKey('palette') && Math.mod(perUnitMap.get(variationParentId).get('palette'), Integer.valueOf(prodToUpdate.Factor__c)) == 0 ?
                    Integer.valueOf(perUnitMap.get(variationParentId).get('palette') / prodToUpdate.Factor__c) : null;
                productsToUpdate.put(prodToUpdate.Id, prodToUpdate);
            }
        }
        if(!productsToUpdate.isEmpty()){
            update productsToUpdate.values();
        }
    }

    public void finish(Database.BatchableContext bc){
        // Do nothing
    }
        
}