force-app/main/default/objects/Product2/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <label>Tenant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>J. J. Darboven GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>Burkhof Kaffee GmbH</fullName>
            </value>
            <value>
                <fullName>J. Eilles GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Internat. GmbH</fullName>
            </value>
            <value>
                <fullName>C.A.Wille Handelsges.mbH &amp; Co.</fullName>
            </value>
            <value>
                <fullName>C.A. Wille Hdl.- u. Verw. gmbH</fullName>
            </value>
            <value>
                <fullName>Andaco Import-u.Handelsges.mbH</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven /NL</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven France</fullName>
            </value>
            <value>
                <fullName>Burkhof Kava spol. s.r.o.</fullName>
            </value>
            <value>
                <fullName>IDEE KAFFEE Ges.m.b.H.</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Poland sp.z o.o.</fullName>
            </value>
            <value>
                <fullName>Burkhof-Kava Slovakia s.r.o.</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Hungaria Kft.</fullName>
            </value>
            <value>
                <fullName>Praxmarer Kaffeevertrieb</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven (Americas), Inc.</fullName>
            </value>
            <value>
                <fullName>Hochstrasser AG</fullName>
            </value>
            <value>
                <fullName>J. Hornig GmbH</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Ireland Ltd.</fullName>
            </value>
            <value>
                <fullName>IDEE Office Coffee Service GmbH</fullName>
            </value>
            <value>
                <fullName>Gourvita GmbH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WebshopProductLink__c/WebshopProductLink__c.object-meta.xml
<CustomObject>
    <description>Product Links for the LWR webshop.</description>
    <label>Webshop Product Link</label>
    <nameField>
        <displayFormat>LINK-{0000000}</displayFormat>
        <label>Webshop Product Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webshop Product Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WebshopProductLink__c/fields/Product1__c.field-meta.xml
<CustomField>
    <fullName>Product1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product1</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>WebshopProductLinksOne</relationshipLabel>
    <relationshipName>WebshopProductLinksOne</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WebshopProductLink__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product2</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>WebshopProductLinksTwo</relationshipLabel>
    <relationshipName>WebshopProductLinksTwo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WebshopProductLinkTriggerTest.cls
@isTest
private class WebshopProductLinkTriggerTest {
    @isTest
    static void testLogic() {
        Product2 product = new Product2();
        product.ExternalId = 'TestProduct';
        product.Name = 'MyTestCoffee';
        product.Tenant__c = '001';
        product.Type = 'Base';
        product.IsActive = true;
        insert product;
        Product2 product2 = new Product2();
        product2.ExternalId = 'TestProduct2';
        product2.Name = 'MyTestCoffee2';
        product2.Tenant__c = '001';
        product2.Type = 'Base';
        product2.IsActive = true;
        insert product2;
        WebshopProductLink__c link = new WebshopProductLink__c(
            Product1__c = product.Id,
            Product2__c = product2.Id
        );
        insert link;
    }
}