force-app/main/default/objects/Account/fields/AssortmentExtended__c.field-meta.xml
<CustomField>
    <fullName>AssortmentExtended__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CRM-1617 Influences visibility of My Products section</description>
    <label>Assortment Extended?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/AssortmentExtensionExclusion__c.field-meta.xml
<CustomField>
    <fullName>AssortmentExtensionExclusion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assortment Extension Exclusion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ConditionChainParent__c.field-meta.xml
<CustomField>
    <fullName>ConditionChainParent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condition Chain Parent</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Condition Chain Parent)</relationshipLabel>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsWebshopAccount__c.field-meta.xml
<CustomField>
    <fullName>IsWebshopAccount__c</fullName>
    <formula>TRUE</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Webshop Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/WebshopFrontpageWarning__c.field-meta.xml
<CustomField>
    <fullName>WebshopFrontpageWarning__c</fullName>
    <label>Webshop Frontpage Warning</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BatchAutomateAssortmentExtension.cls
public class BatchAutomateAssortmentExtension implements Schedulable, Database.Batchable<sObject>, Database.Stateful {
    
    public static final Id ASSORTMENT_EXTENSION_BUYER_GROUP = [SELECT Id FROM BuyerGroup WHERE Name = : System.Label.WebshopDoNotTranslateTeaAndCocayaEntPolicy LIMIT 1].Id;

    public void execute(SchedulableContext sc) {
        Database.executeBatch(new BatchAutomateAssortmentExtension(), 100);
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id FROM Account WHERE IsWebshopAccount__c = TRUE AND AssortmentExtensionExclusion__c = FALSE AND AssortmentExtensionManual__c = FALSE');
    }
    
    public void execute(Database.BatchableContext bc, List<Account> scope) {
        List<BuyerGroupMember> buyerGroupMembersToInsert = new List<BuyerGroupMember>();
        Map<Id, Account> chainAccountsMap = new Map<Id, Account>([
            SELECT Id FROM Account WHERE Id IN : scope AND ConditionChainParent__c != NULL
        ]);
        for(Account ac : scope){
            if(chainAccountsMap.containsKey(ac.Id)){
                ac.AssortmentExtended__c = false;
                //ac.WebshopFrontpageWarning__c = null;
            } else {
                ac.AssortmentExtended__c = true;
                //ac.WebshopFrontpageWarning__c = System.Label.WebshopDoNotTranslateAssortmentExtensionBG;
                buyerGroupMembersToInsert.add(new BuyerGroupMember(
                    BuyerGroupId = ASSORTMENT_EXTENSION_BUYER_GROUP,
                    BuyerId = ac.Id
                ));
            }
        }

        update scope;
        delete [SELECT Id FROM BuyerGroupMember WHERE BuyerGroupId = : ASSORTMENT_EXTENSION_BUYER_GROUP AND BuyerId IN : chainAccountsMap.keySet()];
        if(!buyerGroupMembersToInsert.isEmpty()){
            Database.insert(buyerGroupMembersToInsert, false);
        }
    }

    public void finish(Database.BatchableContext bc){ 
        if(!Test.isRunningTest()){
            Database.executeBatch(new BatchAutomateBrandAssortmentExtension(), 10);
        }
     }
}