force-app/main/default/objects/Account/fields/ChainType__c.field-meta.xml
<CustomField>
    <fullName>ChainType__c</fullName>
    <formula>TEXT(CurrentAccountCondition__r.OwnOrderingRightState__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Chain Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MachineCeditLimit__c.field-meta.xml
<CustomField>
    <fullName>MachineCeditLimit__c</fullName>
    <label>Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/MachineCrefoIndex__c.field-meta.xml
<CustomField>
    <fullName>MachineCrefoIndex__c</fullName>
    <label>Crefo Index</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConditionOverviewHelper__c/ConditionOverviewHelper__c.object-meta.xml
<CustomObject>
    <label>Condition Overview Helper</label>
    <nameField>
        <displayFormat>KH-{000000000}</displayFormat>
        <label>Condition Overview Helper	 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Overview Helpers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConditionOverviewHelper__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Condition Products</relationshipLabel>
    <relationshipName>ConditionOverviewHelpers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConditionOverviewHelper__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Condition Products</relationshipLabel>
    <relationshipName>ConditionOverviewHelpers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MachinePrivateAddress__c.field-meta.xml
<CustomField>
    <fullName>MachinePrivateAddress__c</fullName>
    <label>Private Address</label>
    <type>Address</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MachineSelfEmployedSince__c.field-meta.xml
<CustomField>
    <fullName>MachineSelfEmployedSince__c</fullName>
    <label>Self Employed Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LowestConditionForSalesAreaManager__c.field-meta.xml
<CustomField>
    <fullName>LowestConditionForSalesAreaManager__c</fullName>
    <label>Lowest Condition for Sales Area Manager</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PreviewPrice__c.field-meta.xml
<CustomField>
    <fullName>PreviewPrice__c</fullName>
    <label>Preview Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductGroup__c.field-meta.xml
<CustomField>
    <fullName>ProductGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Product Group)</relationshipLabel>
    <relationshipName>Products_ProductGroup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/InstPurchaseAgreementValidUntil__c.field-meta.xml
<CustomField>
    <fullName>InstPurchaseAgreementValidUntil__c</fullName>
    <label>Inst. Purchase Agreement Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/InterestOnOutstandingPrice__c.field-meta.xml
<CustomField>
    <fullName>InterestOnOutstandingPrice__c</fullName>
    <label>Interest on outstanding price</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/IsMachineOffer__c.field-meta.xml
<CustomField>
    <fullName>IsMachineOffer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Machine Offer?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineCustomerDiscountTotalInEuro__c.field-meta.xml
<CustomField>
    <fullName>MachineCustomerDiscountTotalInEuro__c</fullName>
    <label>Machine Customer Discount Total in Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineDepositMustBePaidUntil__c.field-meta.xml
<CustomField>
    <fullName>MachineDepositMustBePaidUntil__c</fullName>
    <label>Deposit must be paid until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineDirectDebitCollectionDay1or15__c.field-meta.xml
<CustomField>
    <fullName>MachineDirectDebitCollectionDay1or15__c</fullName>
    <label>Direct Debit Collection Day (1st/15th)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <default>true</default>
                <label>01</label>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineDownpaymentBeforeOrAfterOrder__c.field-meta.xml
<CustomField>
    <fullName>MachineDownpaymentBeforeOrAfterOrder__c</fullName>
    <label>Downpayment before or after order</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>before</fullName>
            </value>
            <value>
                <fullName>after</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineFinalRateInEuro__c.field-meta.xml
<CustomField>
    <fullName>MachineFinalRateInEuro__c</fullName>
    <label>Final Rate In Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineFinancingChargePerKG__c.field-meta.xml
<CustomField>
    <fullName>MachineFinancingChargePerKG__c</fullName>
    <formula>( MachineInterestRates__c  -  MachineRoasterDiscountTotalInEuro__c ) /  MachineSalesExpectationCoffee__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Financing Charge per kg</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineInterestRates__c.field-meta.xml
<CustomField>
    <fullName>MachineInterestRates__c</fullName>
    <formula>MachineTotalFinancingAmount__c  * 0.09 *  MachineRuntimeInMonths__c  / 24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Machine Interest Rates</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineLocation__c.field-meta.xml
<CustomField>
    <fullName>MachineLocation__c</fullName>
    <label>Machine Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineMachineAccountBalance__c.field-meta.xml
<CustomField>
    <fullName>MachineMachineAccountBalance__c</fullName>
    <label>Machine Account Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineMerchandiseAccountBalance__c.field-meta.xml
<CustomField>
    <fullName>MachineMerchandiseAccountBalance__c</fullName>
    <label>Merchandise Account Balance</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineMonthlyRateInEuro__c.field-meta.xml
<CustomField>
    <fullName>MachineMonthlyRateInEuro__c</fullName>
    <label>Monthly Rate In Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineNetRevenueCurrentYear__c.field-meta.xml
<CustomField>
    <fullName>MachineNetRevenueCurrentYear__c</fullName>
    <label>Net Revenue Current Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineNetRevenueLastYear__c.field-meta.xml
<CustomField>
    <fullName>MachineNetRevenueLastYear__c</fullName>
    <label>Net Revenue Last Year</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineNotesOnTheContract__c.field-meta.xml
<CustomField>
    <fullName>MachineNotesOnTheContract__c</fullName>
    <label>Notes on the Contract</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineProducerDiscountTotalInEuro__c.field-meta.xml
<CustomField>
    <fullName>MachineProducerDiscountTotalInEuro__c</fullName>
    <label>Machine Producer Discount Total in Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineRecommendationMachineTeam__c.field-meta.xml
<CustomField>
    <fullName>MachineRecommendationMachineTeam__c</fullName>
    <label>Machine Recommendation Machine Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineRentalAgreementEuroPerKG__c.field-meta.xml
<CustomField>
    <fullName>MachineRentalAgreementEuroPerKG__c</fullName>
    <label>Rental Agreement (Euro/kg)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineRoasterDiscountTotalInEuro__c.field-meta.xml
<CustomField>
    <fullName>MachineRoasterDiscountTotalInEuro__c</fullName>
    <label>Machine Roaster Discount Total in Euro</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineRuntimeInMonths__c.field-meta.xml
<CustomField>
    <fullName>MachineRuntimeInMonths__c</fullName>
    <label>Runtime In Months</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineSalesExpectationCoffee__c.field-meta.xml
<CustomField>
    <fullName>MachineSalesExpectationCoffee__c</fullName>
    <label>Sales Expectation Coffee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineSalesExpectationCoffeeperYear__c.field-meta.xml
<CustomField>
    <fullName>MachineSalesExpectationCoffeeperYear__c</fullName>
    <formula>IF( MachineRuntimeInMonths__c  &gt; 0, MachineSalesExpectationCoffee__c  /  MachineRuntimeInMonths__c  * 12,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Expectation Coffee  (in kg) per Ye</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineTotalFinancingAmount__c.field-meta.xml
<CustomField>
    <fullName>MachineTotalFinancingAmount__c</fullName>
    <label>Total Financing Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/MachineTotalMachineValues__c.field-meta.xml
<CustomField>
    <fullName>MachineTotalMachineValues__c</fullName>
    <formula>MachineMachineAccountBalance__c   +  MachineNetAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Machine Total Values</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PriceConfiguratorQuote__c.field-meta.xml
<CustomField>
    <fullName>PriceConfiguratorQuote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Configurator Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quotes (Price Configurator Quote)</relationshipLabel>
    <relationshipName>MachineQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/WKZCoffeeAnnualBonus__c.field-meta.xml
<CustomField>
    <fullName>WKZCoffeeAnnualBonus__c</fullName>
    <label>WKZ Coffee Annual - Bonus</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/WKZCoffeeOneTimeBonus__c.field-meta.xml
<CustomField>
    <fullName>WKZCoffeeOneTimeBonus__c</fullName>
    <label>WKZ Coffee One-Time Bonus</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/WKZCoffeeOneTimeRuntimeMonths__c.field-meta.xml
<CustomField>
    <fullName>WKZCoffeeOneTimeRuntimeMonths__c</fullName>
    <label>WKZ Coffee One-Time - Runtime in Months</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/WKZCoffeeOneTimeTotalRuntime__c.field-meta.xml
<CustomField>
    <fullName>WKZCoffeeOneTimeTotalRuntime__c</fullName>
    <label>WKZ Coffee - One Time - Total Runtime</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/LowestConditionForSalesAreaManager__c.field-meta.xml
<CustomField>
    <fullName>LowestConditionForSalesAreaManager__c</fullName>
    <formula>Product2.LowestConditionForSalesAreaManager__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lowest Condition for Sales Area Manager</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductGroup__c.field-meta.xml
<CustomField>
    <fullName>ProductGroup__c</fullName>
    <label>Product Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RefundDiscountInEuro__c.field-meta.xml
<CustomField>
    <fullName>RefundDiscountInEuro__c</fullName>
    <label>Refund - Discount (in €)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RefundDiscountInPercent__c.field-meta.xml
<CustomField>
    <fullName>RefundDiscountInPercent__c</fullName>
    <label>Refund - Discount (in %)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/QuoteInstallmentPurchasePlanController.cls
public without sharing class QuoteInstallmentPurchasePlanController {
    @AuraEnabled(cacheable=false)
    public static String findAndConnectLatestQuote(String quoteId){
        try {
            Quote qOld = [SELECT Id, AccountId FROM Quote WHERE Id = : quoteId];
            List<Quote> ql = [SELECT Id FROM Quote 
                WHERE Opportunity.StageName = 'Closed Won' AND AccountId = : qOld.AccountId AND IsMachineOffer__c = FALSE ORDER BY Opportunity.CreatedDate DESC LIMIT 1];
            if(!ql.isEmpty()){
                Quote q = new Quote(Id = quoteId, PriceConfiguratorQuote__c = ql[0].Id);
                update q;
                return 'success';
            } else {
                Quote q = new Quote(Id = quoteId, PriceConfiguratorQuote__c = null);
                update q;
                return 'success';
            }
        } catch(Exception e){
            return e.getMessage();
        }
    }

    @AuraEnabled(cacheable=false)
    public static void handleSaveAccountQuote(String contactId, String quoteId, String accountId, Map<String, String> contactData, Map<String, String> quoteData, Map<String, String> accountData){
        if(contactId != null && contactData != null && !contactData.isEmpty()){
            Contact c = new Contact(Id = contactId);
            Map<String, String> fieldTypeMap = getFieldTypeMap('Contact');
            for(String fieldName : contactData.keySet()){
                String lowerFieldName = fieldName.toLowerCase();
                if(fieldTypeMap.containsKey(lowerFieldName)){
                    if(fieldTypeMap.get(lowerFieldName) == 'date'){
                        c.put(fieldName, Date.valueOf(contactData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'datetime'){
                        c.put(fieldName, DateTime.valueOf(contactData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'numeric'){
                        c.put(fieldName, Decimal.valueOf(contactData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'boolean'){
                        c.put(fieldName, String.valueOf(contactData.get(fieldName)) == 'true');
                    } else {
                        c.put(fieldName, String.valueOf(contactData.get(fieldName)));
                    }
                } else if(fieldName.endsWith('__s')){
                    c.put(fieldName, String.valueOf(contactData.get(fieldName)));
                }
            }
            update c;
        }
        if(quoteId != null && quoteData != null && !quoteData.isEmpty()){
            Quote q = new Quote(Id = quoteId);
            Map<String, String> fieldTypeMap = getFieldTypeMap('Quote');
            for(String fieldName : quoteData.keySet()){
                String lowerFieldName = fieldName.toLowerCase();
                if(fieldTypeMap.containsKey(lowerFieldName)){
                    if(fieldTypeMap.get(lowerFieldName) == 'date'){
                        q.put(fieldName, Date.valueOf(quoteData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'datetime'){
                        q.put(fieldName, DateTime.valueOf(quoteData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'numeric'){
                        q.put(fieldName, Decimal.valueOf(quoteData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'boolean'){
                        q.put(fieldName, String.valueOf(quoteData.get(fieldName)) == 'true');
                    } else {
                        q.put(fieldName, String.valueOf(quoteData.get(fieldName)));
                    }
                }
            }
            update q;
        }
        if(accountId != null && accountData != null && !accountData.isEmpty()){
            Account ac = new Account(Id = accountId);
            Map<String, String> fieldTypeMap = getFieldTypeMap('Account');
            for(String fieldName : accountData.keySet()){
                String lowerFieldName = fieldName.toLowerCase();
                if(fieldTypeMap.containsKey(lowerFieldName)){
                    if(fieldTypeMap.get(lowerFieldName) == 'date'){
                        ac.put(fieldName, Date.valueOf(accountData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'datetime'){
                        ac.put(fieldName, DateTime.valueOf(accountData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'numeric'){
                        ac.put(fieldName, Decimal.valueOf(accountData.get(fieldName)));
                    } else if(fieldTypeMap.get(lowerFieldName) == 'boolean'){
                        ac.put(fieldName, String.valueOf(accountData.get(fieldName)) == 'true');
                    } else {
                        ac.put(fieldName, String.valueOf(accountData.get(fieldName)));
                    }
                }
            }
            update ac;
        }
    }

    private static Map<String, String> getFieldTypeMap(String sobjectName) {
        Map<String, String> result = new Map<String, String>();

        Schema.SObjectType objType = Schema.getGlobalDescribe().get(sobjectName);
        if (objType == null) return result;

        Map<String, Schema.SObjectField> fields = objType.getDescribe().fields.getMap();

        for (String fieldName : fields.keySet()) {
            Schema.DisplayType dt = fields.get(fieldName).getDescribe().getType();
            String simpleType;

            switch on dt {
                when Date           { simpleType = 'date'; }
                when DateTime       { simpleType = 'datetime'; }
                when Double,
                    Integer,
                    Long,
                    Currency,
                    Percent         { simpleType = 'numeric'; }
                when Boolean        { simpleType = 'boolean'; }
                when else           { simpleType = 'string'; }
            }

            result.put(fieldName, simpleType);
        }
        return result;
    }

    @AuraEnabled(cacheable=false)
    public static QuoteWrapper getData(String quoteId){
        Quote q = [SELECT Id, OpportunityId, ContactId, AccountId,
            Contact.MachineSelfEmployedSince__c, Contact.MachinePrivateAddress__c, Contact.Birthdate, Contact.FirstName, Contact.LastName,
            Account.Name, Account.ShippingStreet, Account.ShippingCity, Account.ShippingPostalCode, Account.CreatedDate, Account.AccountNumber, 
            Account.ChainType__c, 
            //Account.SalesQuantityLYTotal__c, Account.SalesQuantityCYToday__c, 
            MachineLocation__c,
            Account.MachineCrefoIndex__c,
            Account.MachineCeditLimit__c, 
            MachineTotalFinancingAmount__c,
            MachineRuntimeInMonths__c, MachineDepositMustBePaidUntil__c,
            MachineProducerDiscountTotalInEuro__c, MachineMonthlyRateInEuro__c, MachineCustomerDiscountTotalInEuro__c,
            MachineFinalRateInEuro__c, MachineRoasterDiscountTotalInEuro__c, 
            MachineInterestRates__c, 
            MachineRentalAgreementEuroPerKG__c,
            MachineFinancingChargePerKG__c,
            InstPurchaseAgreementValidUntil__c,
            MachineNotesOnTheContract__c,
            MachineMerchandiseAccountBalance__c, MachineMachineAccountBalance__c, MachineTotalMachineValues__c, 
            MachineSalesExpectationCoffee__c, MachineSalesExpectationCoffeeperYear__c, MachineNetRevenueCurrentYear__c, MachineNetRevenueLastYear__c, 
            MachineDownpaymentBeforeOrAfterOrder__c, MachineDirectDebitCollectionDay1or15__c, InterestOnOutstandingPrice__c,
            MachineRecommendationMachineTeam__c,
            PriceConfiguratorQuote__c
        FROM Quote WHERE Id = : quoteId];
        String profileName = [SELECT Id, Profile.Name FROM User WHERE Id = : UserInfo.getUserId()].Profile?.Name;
        QuoteWrapper wrapper = new QuoteWrapper(q, q.AccountId != null ? q.Account : null, q.ContactId != null ? q.Contact : null, profileName);
        return wrapper;
    }

    public class ProductWrapper{
        @AuraEnabled public Id id {get; set;}
        @AuraEnabled public String name {get; set;}
        @AuraEnabled public Decimal vkPriceCustomer {get; set;}
        @AuraEnabled public Decimal vlPrice {get; set;}
        @AuraEnabled public Decimal rvInPercent {get; set;}
        @AuraEnabled public Decimal rvInPercentDisplay {get; set;}
        @AuraEnabled public Decimal rvInEuro {get; set;}
        @AuraEnabled public Decimal wkzEuroPerKg {get; set;}
        @AuraEnabled public Decimal rentalContactEuroPerKg {get; set;}
        @AuraEnabled public Decimal financingEuroPerKg {get; set;}
        @AuraEnabled public Decimal netSalePrice {get; set;}
        @AuraEnabled public Decimal vsPrice {get; set;}
        @AuraEnabled public Decimal winLossEuroPerKg {get; set;}
        public ProductWrapper(Id id, String name, Decimal vkPriceCustomer, Decimal vlPrice, Decimal rvInPercent, Decimal rvInEuro, Decimal wkzEuroPerKg, Decimal rentalContactEuroPerKg, Decimal financingEuroPerKg, Decimal vsPrice){
            this.id = id;
            this.name = name;
            this.vkPriceCustomer = vkPriceCustomer;
            this.vlPrice = vlPrice;
            this.rvInPercent = rvInPercent;
            this.rvInPercentDisplay = rvInPercent != null ? rvInPercent / 100 : null;
            this.rvInEuro = rvInEuro;
            this.wkzEuroPerKg = wkzEuroPerKg;
            this.rentalContactEuroPerKg = rentalContactEuroPerKg;
            this.financingEuroPerKg = financingEuroPerKg;
            this.netSalePrice = (this.vkPriceCustomer ?? 0) - ( (((this.vkPriceCustomer ?? 0) * (this.rvInPercent ?? 0)) / 100) + (this.rvInEuro ?? 0) + (this.wkzEuroPerKg ?? 0) + (this.rentalContactEuroPerKg ?? 0) + (this.financingEuroPerKg ?? 0) );
            this.vsPrice = vsPrice;
            this.winLossEuroPerKg = (this.netSalePrice ?? 0) - (this.vsPrice ?? 0);
        }
    }

    public class QuoteWrapper{
        @AuraEnabled public Id groupId {get; set;}
        @AuraEnabled public Account accountData {get; set;}
        @AuraEnabled public Contact contactData {get; set;}
        @AuraEnabled public Quote quoteData {get; set;}
        @AuraEnabled public Boolean hasPriceConfiguratorQuote {get; set;}
        @AuraEnabled public Boolean isGLOnly {get; set;}
        @AuraEnabled public Boolean isAdminOrGL {get; set;}
        @AuraEnabled public Boolean isAdminOrMachineTeam {get; set;}
        @AuraEnabled public Boolean hasAccount {get; set;}
        @AuraEnabled public Boolean hasContact {get; set;}
        @AuraEnabled public List<ProductWrapper> products {get; set;}
        @AuraEnabled public Decimal salesQuantityLY {get; set;}
        @AuraEnabled public Decimal salesQuantityCY {get; set;}
        public QuoteWrapper(Quote q, Account ac, Contact con, String profileName){
            this.quoteData = q;
            this.accountData = ac;
            this.contactData = con;
            this.hasPriceConfiguratorQuote = q.PriceConfiguratorQuote__c != null;
            this.hasAccount = ac != null;
            this.hasContact = con != null;
            this.salesQuantityLY = 0;
            this.salesQuantityCY = 0;
            this.isGLOnly = (String.isBlank(profileName) || !profileName.endsWith('dministrator')) && FeatureManagement.checkPermission('QuoteInstallmentGLFields') && !FeatureManagement.checkPermission('QuoteInstallmentMachineTeamFields');
            this.isAdminOrGL = (String.isNotBlank(profileName) && profileName.endsWith('dministrator')) || FeatureManagement.checkPermission('QuoteInstallmentGLFields');
            this.isAdminOrMachineTeam = (String.isNotBlank(profileName) && profileName.endsWith('dministrator')) || FeatureManagement.checkPermission('QuoteInstallmentMachineTeamFields');
            List<ProductWrapper> productWrappers = new List<ProductWrapper>();
            if(this.hasPriceConfiguratorQuote){
                for(Quote nonMachineQuote : [SELECT Id, MachineRentalAgreementEuroPerKG__c,
                    WKZCoffeeOneTimeRuntimeMonths__c, WKZCoffeeOneTimeBonus__c,
                    WKZCoffeeAnnualBonus__c, WKZCoffeeOneTimeTotalRuntime__c,
                    (SELECT Id, Product2Id, Product2.LowestConditionForSalesAreaManager__c, Product2.PreviewPrice__c, Product2.Name, UnitPrice, RefundDiscountInPercent__c, RefundDiscountInEuro__c FROM QuoteLineItems WHERE (NOT Product2.Name  LIKE 'Produkt-Untergruppe%') AND Product2.ProductGroup__r.Name LIKE '%Röstkaffee'),
                    (SELECT Id, Product__r.ProductGroup__r.Name, Product__c, Product__r.LowestConditionForSalesAreaManager__c, Product__r.PreviewPrice__c, Product__r.Name, Price__c, Quote__c, QuoteLineItem__c, QuoteLineItem__r.RefundDiscountInPercent__c, QuoteLineItem__r.RefundDiscountInEuro__c FROM ConditionOverviewHelpers__r WHERE Product__r.ProductGroup__r.Name LIKE '%Röstkaffee')        
                FROM Quote WHERE Id = : q.PriceConfiguratorQuote__c]){
                    productWrappers = processProductWrappers(q, productWrappers, nonMachineQuote);
                }
            } else {
                for(Quote nonMachineQuote : [SELECT Id, MachineRentalAgreementEuroPerKG__c,
                    WKZCoffeeOneTimeRuntimeMonths__c, WKZCoffeeOneTimeBonus__c,
                    WKZCoffeeAnnualBonus__c, WKZCoffeeOneTimeTotalRuntime__c,
                    (SELECT Id, Product2Id, Product2.LowestConditionForSalesAreaManager__c, Product2.PreviewPrice__c, Product2.Name, UnitPrice, RefundDiscountInPercent__c, RefundDiscountInEuro__c FROM QuoteLineItems WHERE (NOT Product2.Name  LIKE 'Produkt-Untergruppe%') AND Product2.ProductGroup__r.Name LIKE '%Röstkaffee'),
                    (SELECT Id, Product__r.ProductGroup__r.Name, Product__c, Product__r.LowestConditionForSalesAreaManager__c, Product__r.PreviewPrice__c, Product__r.Name, Price__c, Quote__c, QuoteLineItem__c, QuoteLineItem__r.RefundDiscountInPercent__c, QuoteLineItem__r.RefundDiscountInEuro__c FROM ConditionOverviewHelpers__r WHERE Product__r.ProductGroup__r.Name LIKE '%Röstkaffee')        
                FROM Quote 
                WHERE Opportunity.StageName = 'Closed Won' AND AccountId = : q.AccountId AND IsMachineOffer__c = FALSE ORDER BY Opportunity.CreatedDate DESC
                LIMIT 1]){
                    productWrappers = processProductWrappers(q, productWrappers, nonMachineQuote);
                    q.PriceConfiguratorQuote__c = nonMachineQuote.Id;
                    update q;
                }
            }
            /*if(this.hasAccount){
                List<BoughtProductGroupsC__c> groups = [SELECT Id, Name, SalesQuantityLYTotal__c, SalesQuantityCYToday__c FROM BoughtProductGroupsC__c WHERE ProductClass__c = 'RÖSTKAFFEE' AND CustomerReferenceID__c = : ac.Id];
                if(!groups.isEmpty()){
                    this.salesQuantityLY = groups[0].SalesQuantityLYTotal__c;
                    this.salesQuantityCY = groups[0].SalesQuantityCYToday__c;
                }
            }*/
            this.products = productWrappers;
        }
    }

    private static List<ProductWrapper> processProductWrappers(Quote q, List<ProductWrapper> productWrappers, Quote nonMachineQuote){
        // WKZ: ((WKZ annual/12) * Runtime Months) / Absatzmenge) + (WKZ einmal / Absatzmenge)
        Decimal wkz = 0;
        if(nonMachineQuote.WKZCoffeeOneTimeTotalRuntime__c != null){
            Decimal amount = (Decimal) nonMachineQuote.WKZCoffeeOneTimeTotalRuntime__c;
            Decimal onetime = (Decimal) nonMachineQuote.WKZCoffeeOneTimeBonus__c ?? 0;
            Decimal annual = (Decimal) nonMachineQuote.WKZCoffeeAnnualBonus__c ?? 0;
            Decimal runtime = (Decimal) nonMachineQuote.WKZCoffeeOneTimeRuntimeMonths__c ?? 0;
            wkz = ((((annual / 12) * runtime) / amount) + (onetime / amount)).setScale(2);
        }

        for(QuoteLineItem qli : nonMachineQuote.QuoteLineItems){
            productWrappers.add(new ProductWrapper(qli.Product2Id, qli.Product2.Name, qli.UnitPrice, qli.Product2.LowestConditionForSalesAreaManager__c, qli.RefundDiscountInPercent__c ?? 0, qli.RefundDiscountInEuro__c ?? 0, wkz, q.MachineRentalAgreementEuroPerKG__c, q.MachineFinancingChargePerKG__c, qli.Product2.PreviewPrice__c));
        }
        for(ConditionOverviewHelper__c helper : nonMachineQuote.ConditionOverviewHelpers__r){
            productWrappers.add(new ProductWrapper(helper.Product__c, helper.Product__r.Name, helper.Price__c, helper.Product__r.LowestConditionForSalesAreaManager__c, helper.QuoteLineItem__r.RefundDiscountInPercent__c ?? 0, helper.QuoteLineItem__r.RefundDiscountInEuro__c, wkz, q.MachineRentalAgreementEuroPerKG__c, q.MachineFinancingChargePerKG__c, helper.Product__r.PreviewPrice__c));
        }
        return productWrappers;
    }
}