force-app/main/default/objects/Account/fields/CreateOrActivateBuyerAccount__c.field-meta.xml
<CustomField>
    <fullName>CreateOrActivateBuyerAccount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Or Activate Buyer Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ERPCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>ERPCustomerNumber__c</fullName>
    <description>A unique external customer number to identify the correct integration record in the ERP system.</description>
    <externalId>true</externalId>
    <label>ERP Customer Number</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WebshopBatchCreateActivateBuyerAccTest.cls
@isTest
public with sharing class WebshopBatchCreateActivateBuyerAccTest {
    @isTest 
    private static void testLogic(){
        BuyerGroup bg = new BuyerGroup(Name = 'Standard');
        insert bg;
        WebStore webStore2 = new WebStore(
            Name='J.J. Darboven LWR Shop'
        );
        insert webStore2;
        // Create mock CommerceEntitlementProduct and Account records
        Account acc1 = new Account(Name = 'Test Account 1', ERPCustomerNumber__c = 'CUST001', CreateOrActivateBuyerAccount__c = TRUE);
        insert acc1;
        Test.startTest();
            System.enqueueJob(new WebshopQueueCreateActivateBuyerAccount());
        Test.stopTest();
        Assert.areEqual([SELECT Id FROM BuyerAccount].size(), 1);
    }
}