force-app/main/default/objects/Account/fields/ERPCustomerNumber__c.field-meta.xml
<CustomField>
    <fullName>ERPCustomerNumber__c</fullName>
    <description>A unique external customer number to identify the correct integration record in the ERP system.</description>
    <externalId>true</externalId>
    <label>ERP Customer Number</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountBrandAssignment__c/AccountBrandAssignment__c.object-meta.xml
<CustomObject>
    <label>Account Brand Assignment</label>
    <nameField>
        <displayFormat>ABA-{0000000}</displayFormat>
        <label>Account Brand Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Brand Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountBrandAssignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Brand Assignments</relationshipLabel>
    <relationshipName>AccountBrandAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBrandAssignment__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Brand has to be Assortment Extension Enabled.</errorMessage>
        <filterItems>
            <field>WebshopBrand__c.AssortmentExtensionEnabled__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>WebshopBrand__c</referenceTo>
    <relationshipLabel>Account Brand Assignments</relationshipLabel>
    <relationshipName>AccountBrandAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WebshopBrand__c/WebshopBrand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WebshopBrand__c/fields/AssortmentExtensionEnabled__c.field-meta.xml
<CustomField>
    <fullName>AssortmentExtensionEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CRM-1669</description>
    <label>Assortment Extension Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MigrationAccountBrandJob.cls
public class MigrationAccountBrandJob implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {

    public Map<String, Id> activeBrands = new Map<String, Id>();
    public Database.QueryLocator start(Database.BatchableContext bc){

        for(WebshopBrand__c brand : [SELECT Id, Name FROM WebshopBrand__c WHERE AssortmentExtensionEnabled__c = TRUE]){
            this.activeBrands.put(brand.Name, brand.Id);
        }
        return Database.getQueryLocator([
            SELECT Id, ERPCustomerNumber__c, (SELECT Id, Brand__r.Name FROM AccountBrandAssignments__r)
            FROM Account
            WHERE ERPCustomerNumber__c != NULL
        ]);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope){

        List<Account> accounts = (List<Account>)scope;
        Set<String> identifiers = new Set<String>();
        Map<Id, Set<String>> existingBrandsByAcc = new Map<Id, Set<String>>();

        for(Account ac : accounts){
            identifiers.add(ac.ERPCustomerNumber__c);
            Set<String> innerSet = new Set<String>();
            for(AccountBrandAssignment__c aba : ac.AccountBrandAssignments__r){
                innerSet.add(aba.Brand__r.Name);
            }
            existingBrandsByAcc.put(ac.Id, innerSet);
        }

        if(identifiers.isEmpty()) return;

        Map<String, Set<String>> accountToBrands = new Map<String, Set<String>>();

        Set<String> brandNames = this.activeBrands.keySet();
        for(Object rowPre : SourceOrgApi.query(
            'SELECT Id, Brand__c, Brand__r.Name, Account__r.AccountNumber ' + 
            'FROM AccountBrandAssignment__c WHERE Account.AccountNumber IN (\'' +
            String.join(new List<String>(identifiers), '\',\'') + '\') AND Brand__r.Name IN (\'' +
            String.join(new List<String>(brandNames), '\',\'') + '\')'
        )){
            Map<String,Object> row = (Map<String,Object>)rowPre;
            Map<String,Object> acc = (Map<String,Object>) row.get('Account');
            Map<String,Object> brd = (Map<String,Object>) row.get('Brand__r');
            String accountNumber = (String)acc.get('AccountNumber');
            String brandName = (String)brd.get('Name');
            if(accountNumber == null) continue;
            Set<String> innerSet = accountToBrands.containsKey(accountNumber) ? accountToBrands.get(accountNumber) : new Set<String>();
            innerSet.add(brandName);
            accountToBrands.put(accountNumber, innerSet);
        }

        List<AccountBrandAssignment__c> abaToInsert = new List<AccountBrandAssignment__c>();
        for(Account ac : accounts){
            Set<String> existingBrands = existingBrandsByAcc.containsKey(ac.Id) ? existingBrandsByAcc.get(ac.Id) : new Set<String>();
            if(accountToBrands.containsKey(ac.ERPCustomerNumber__c)){
                for(String newBrand : accountToBrands.get(ac.ERPCustomerNumber__c)){
                    if(!existingBrands.contains(newBrand) && this.activeBrands.containsKey(newBrand)){
                        abaToInsert.add(new AccountBrandAssignment__c(
                            Account__c = ac.Id,
                            Brand__c = this.activeBrands.get(newBrand)
                        ));
                    }
                }
            }
        }
        if(!abaToInsert.isEmpty()){
            Database.insert(abaToInsert, false);
        }
    }

    public void finish(Database.BatchableContext bc){
        // Do nothing
    }
}