force-app/main/default/objects/Account/fields/HasActiveCustomer__c.field-meta.xml
<CustomField>
    <fullName>HasActiveCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Active Customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsWebshopAccount__c.field-meta.xml
<CustomField>
    <fullName>IsWebshopAccount__c</fullName>
    <formula>TRUE</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Webshop Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WebshopActiveCustomerCheckBatch.cls
/**
* Processor for checking whether webshop customer is active. CRM-575
* @author: Stanley Yin (stanley.yin@nfq-x.com), Dec 17, 2023
*
*/

public without sharing class WebshopActiveCustomerCheckBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, (SELECT Id FROM Contacts WHERE ActiveWebshopUser__c = TRUE), (SELECT Id FROM ManagedAccount) FROM Account WHERE IsWebshopAccount__c = TRUE]);
    }
    
    public void execute(Database.BatchableContext bc, List<Account> scope){
        for(Account ac : scope){
            ac.HasActiveCustomer__c = !ac.Contacts.isEmpty() || !ac.ManagedAccount.isEmpty();
        }
        update scope;
    } 
    
    public void finish(Database.BatchableContext bc){ 
        // No actions
    }  
}