force-app/main/default/objects/Account/fields/LetterCampaignActivated__c.field-meta.xml
<CustomField>
    <fullName>LetterCampaignActivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Letter Campaign Activated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LetterCampaignBonusUsed__c.field-meta.xml
<CustomField>
    <fullName>LetterCampaignBonusUsed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Letter Campaign Bonus Used</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Books</relationshipLabel>
    <relationshipName>Price_Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <label>Tenant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>J. J. Darboven GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>Burkhof Kaffee GmbH</fullName>
            </value>
            <value>
                <fullName>J. Eilles GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Internat. GmbH</fullName>
            </value>
            <value>
                <fullName>C.A.Wille Handelsges.mbH &amp; Co.</fullName>
            </value>
            <value>
                <fullName>C.A. Wille Hdl.- u. Verw. gmbH</fullName>
            </value>
            <value>
                <fullName>Andaco Import-u.Handelsges.mbH</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven /NL</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven France</fullName>
            </value>
            <value>
                <fullName>Burkhof Kava spol. s.r.o.</fullName>
            </value>
            <value>
                <fullName>IDEE KAFFEE Ges.m.b.H.</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Poland sp.z o.o.</fullName>
            </value>
            <value>
                <fullName>Burkhof-Kava Slovakia s.r.o.</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Hungaria Kft.</fullName>
            </value>
            <value>
                <fullName>Praxmarer Kaffeevertrieb</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven (Americas), Inc.</fullName>
            </value>
            <value>
                <fullName>Hochstrasser AG</fullName>
            </value>
            <value>
                <fullName>J. Hornig GmbH</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Ireland Ltd.</fullName>
            </value>
            <value>
                <fullName>IDEE Office Coffee Service GmbH</fullName>
            </value>
            <value>
                <fullName>Gourvita GmbH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AbandonedCartCheckoutDeleteTest.cls
@isTest
private class AbandonedCartCheckoutDeleteTest {
    @testSetup
    static void setup() {
        
        // Insert test products corresponding to the labels
        Product2 firstStageProduct = new Product2(Name = 'test1', Tenant__c = '001', ProductCode = System.Label.LetterCampaignBonusFirstStageItemCode);
        Product2 secondStageProduct = new Product2(Name = 'test2', Tenant__c = '001', ProductCode = System.Label.LetterCampaignBonusSecondStageItemCode);
        Decimal productPrice = (Decimal.valueOf(System.Label.LetterCampaignBonusFirstStageThreshold) + Decimal.valueOf(System.Label.LetterCampaignBonusSecondStageThreshold)) / 4;
        Product2 myProduct = new Product2(Name = 'test3', Tenant__c = '001', ProductCode = '123');
        insert new List<Product2>{ firstStageProduct, secondStageProduct, myProduct };
    
        Account account = WebCartTriggerHandlerTest.generateAccount(true, false);
        account.LetterCampaignActivated__c = true;
        account.LetterCampaignBonusUsed__c = false;
        insert account;

        Pricebook2 buyersbook = new Pricebook2();
        buyersbook.Name = 'BuyerBook1';
        buyersbook.isActive = true;
        buyersbook.Account__c = account.Id;
        insert buyersbook;

        PricebookEntry entryForProduct = new PricebookEntry();
        entryForProduct.Pricebook2Id = Test.getStandardPricebookId();
        entryForProduct.Product2Id = myProduct.Id;
        entryForProduct.UnitPrice = productPrice;
        entryForProduct.IsActive = TRUE;
        insert entryForProduct;

        PricebookEntry cstEntryForProduct = new PricebookEntry();
        cstEntryForProduct.Pricebook2Id = buyersbook.Id;
        cstEntryForProduct.Product2Id = myProduct.Id;
        cstEntryForProduct.UnitPrice = productPrice;
        cstEntryForProduct.IsActive = TRUE;
        insert cstEntryForProduct;
        // Insert test account

        WebStore testWebStore = new WebStore(Name='TestWebStore');
        insert testWebStore;
        // Create test WebCart records before and simulate an update that triggers the logic
        WebCart cart = new WebCart(Name = 'Cart', WebStoreId = testWebStore.Id, AccountId=account.Id, Status = 'Checkout', CreatedDate = Datetime.now().addDays(-30), LastModifiedDate = Datetime.now().addDays(-30));
        insert cart;
    }

    @isTest
    static void testBatch() {
        // Test the Batchable execute method
        Test.startTest();
            Database.executeBatch(new AbandonedCartCheckoutDeleteBatch(), 1);
        Test.stopTest();

        // Verify the outcome
        List<WebCart> updatedCarts = [SELECT Id FROM WebCart];
        System.assertEquals(0, updatedCarts.size());
    }
}