force-app/main/default/objects/Account/fields/LetterCampaignBonusUsed__c.field-meta.xml
<CustomField>
    <fullName>LetterCampaignBonusUsed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Letter Campaign Bonus Used</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/FreeReason__c.field-meta.xml
<CustomField>
    <fullName>FreeReason__c</fullName>
    <description>This field should be filled when the OrderItem is sold for free. It is used in the ERP to explain why the product was sold for free</description>
    <label>FreeReason</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <label>Tenant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>J. J. Darboven GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>Burkhof Kaffee GmbH</fullName>
            </value>
            <value>
                <fullName>J. Eilles GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Internat. GmbH</fullName>
            </value>
            <value>
                <fullName>C.A.Wille Handelsges.mbH &amp; Co.</fullName>
            </value>
            <value>
                <fullName>C.A. Wille Hdl.- u. Verw. gmbH</fullName>
            </value>
            <value>
                <fullName>Andaco Import-u.Handelsges.mbH</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven /NL</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven France</fullName>
            </value>
            <value>
                <fullName>Burkhof Kava spol. s.r.o.</fullName>
            </value>
            <value>
                <fullName>IDEE KAFFEE Ges.m.b.H.</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Poland sp.z o.o.</fullName>
            </value>
            <value>
                <fullName>Burkhof-Kava Slovakia s.r.o.</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Hungaria Kft.</fullName>
            </value>
            <value>
                <fullName>Praxmarer Kaffeevertrieb</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven (Americas), Inc.</fullName>
            </value>
            <value>
                <fullName>Hochstrasser AG</fullName>
            </value>
            <value>
                <fullName>J. Hornig GmbH</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Ireland Ltd.</fullName>
            </value>
            <value>
                <fullName>IDEE Office Coffee Service GmbH</fullName>
            </value>
            <value>
                <fullName>Gourvita GmbH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderTriggerTest.cls
@isTest
public class OrderTriggerTest {
    public static List<Account> createTestAccounts(Integer count) {
        List<Account> accounts = new List<Account>();
        for (Integer i = 0; i < count; i++) {
            accounts.add(new Account(Name = 'Test Account ' + i, LetterCampaignBonusUsed__c = false));
        }
        insert accounts;
        return accounts;
    }

    public static List<Order> createTestOrders(List<Account> accounts, String status, Boolean modifiedCreatedDate) {
        List<Order> orders = new List<Order>();
        for (Account acc : accounts) {
            Order o = new Order(AccountId = acc.Id, Status = status, EffectiveDate = Date.today());
            if(modifiedCreatedDate){
                o.CreatedDate = Date.today().addDays(-2);
                o.LastModifiedDate = Date.today().addDays(-2);
            }
            orders.add(o);
        }
        insert orders;
        return orders;
    }

    public static List<OrderItem> createOrderItems(List<Order> orders, Boolean isFreeItem) {
        List<OrderItem> items = new List<OrderItem>();
        Product2 prod = new Product2(
        	Name='Test Product',
            Tenant__c = '001'
        );
        insert prod;
        for (Order order : orders) {
            items.add(new OrderItem(OrderId = order.Id, FreeReason__c = isFreeItem ? System.Label.LetterCampaignFreeReason : '', Product2Id = prod.Id, Quantity = 1, UnitPrice = Decimal.valueOf(System.Label.LetterCampaignBonusSecondStageThreshold) + 1, ListPrice = Decimal.valueOf(System.Label.LetterCampaignBonusSecondStageThreshold) + 1));
        }
        insert items;
        return items;
    }


    @isTest
    static void testOrderActivationWithUnusedBonus() {
        List<Account> accounts = createTestAccounts(1);
        List<Order> orders = createTestOrders(accounts, 'Draft', false);
        List<OrderItem> items = createOrderItems(orders, true);

        Test.startTest();
        // Simulate order activation
        for (Order ord : orders) {
            ord.Status = OrderTriggerHandler.ACTIVATED_STATUS;
        }
        update orders;
        Test.stopTest();

        // Verify Account Bonus Usage
        Account updatedAccount = [SELECT LetterCampaignBonusUsed__c FROM Account WHERE Id = :accounts[0].Id];
        System.assert(updatedAccount.LetterCampaignBonusUsed__c, 'The letter campaign bonus should be marked as used.');
    }

    @isTest
    static void testOrderActivationWithUsedBonus() {
        List<Account> accounts = createTestAccounts(1);
        accounts[0].LetterCampaignBonusUsed__c = true;
        update accounts;

        List<Order> orders = createTestOrders(accounts, 'Draft', false);
        List<OrderItem> items = createOrderItems(orders, true);

        Test.startTest();
        // Simulate order activation
        for (Order ord : orders) {
            ord.Status = OrderTriggerHandler.ACTIVATED_STATUS;
            try {
                update ord;
            } catch (DmlException e) {
                System.assert(e.getMessage().contains(OrderTriggerHandler.LETTER_BONUS_ERROR), 'Expected an error when bonus is already used');
            }
        }
        Test.stopTest();
    }

    @isTest
    static void testNonActivatedOrder() {
        List<Account> accounts = createTestAccounts(1);
        List<Order> orders = createTestOrders(accounts, 'Draft', false);
        List<OrderItem> items = createOrderItems(orders, true);

        Test.startTest();
        update orders; // No status change to 'Activated'
        Test.stopTest();

        // Verify that no changes have been made to accounts
        Account refreshedAccount = [SELECT LetterCampaignBonusUsed__c FROM Account WHERE Id = :accounts[0].Id];
        System.assert(!refreshedAccount.LetterCampaignBonusUsed__c, 'No changes should be made to the account.');
    }
}