force-app/main/default/objects/BuyerGroup/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRM-1669</description>
    <label>Brand</label>
    <referenceTo>WebshopBrand__c</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>BuyerGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BuyerGroupMember/fields/Dynamic__c.field-meta.xml
<CustomField>
    <fullName>Dynamic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dynamic?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommerceEntitlementPolicy/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRM-1669</description>
    <label>Brand</label>
    <referenceTo>WebshopBrand__c</referenceTo>
    <relationshipLabel>Entitlement Policies</relationshipLabel>
    <relationshipName>EntitlementPolicies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Mövenpick</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/BrandWebshop__c.field-meta.xml
<CustomField>
    <fullName>BrandWebshop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Webshop</label>
    <referenceTo>WebshopBrand__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tenant__c.field-meta.xml
<CustomField>
    <fullName>Tenant__c</fullName>
    <label>Tenant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>J. J. Darboven GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>Burkhof Kaffee GmbH</fullName>
            </value>
            <value>
                <fullName>J. Eilles GmbH &amp; Co. KG</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Internat. GmbH</fullName>
            </value>
            <value>
                <fullName>C.A.Wille Handelsges.mbH &amp; Co.</fullName>
            </value>
            <value>
                <fullName>C.A. Wille Hdl.- u. Verw. gmbH</fullName>
            </value>
            <value>
                <fullName>Andaco Import-u.Handelsges.mbH</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven /NL</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven France</fullName>
            </value>
            <value>
                <fullName>Burkhof Kava spol. s.r.o.</fullName>
            </value>
            <value>
                <fullName>IDEE KAFFEE Ges.m.b.H.</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Poland sp.z o.o.</fullName>
            </value>
            <value>
                <fullName>Burkhof-Kava Slovakia s.r.o.</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Hungaria Kft.</fullName>
            </value>
            <value>
                <fullName>Praxmarer Kaffeevertrieb</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven (Americas), Inc.</fullName>
            </value>
            <value>
                <fullName>Hochstrasser AG</fullName>
            </value>
            <value>
                <fullName>J. Hornig GmbH</fullName>
            </value>
            <value>
                <fullName>J.J. Darboven Ireland Ltd.</fullName>
            </value>
            <value>
                <fullName>IDEE Office Coffee Service GmbH</fullName>
            </value>
            <value>
                <fullName>Gourvita GmbH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WebshopBrand__c/WebshopBrand__c.object-meta.xml
<CustomObject>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WebshopBrand__c/fields/AssortmentExtensionEnabled__c.field-meta.xml
<CustomField>
    <fullName>AssortmentExtensionEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CRM-1669</description>
    <label>Assortment Extension Enabled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchAutomateBrandAssortmentExtTest.cls
@IsTest
private class BatchAutomateBrandAssortmentExtTest {

    @TestSetup
    static void setup() {

        WebStore webStore = new WebStore(
            Name=System.Label.WebshopDoNotTranslateStoreName
        );
        insert webStore;

        ProductCatalog myCatalog = new ProductCatalog(Name = 'test');
        insert myCatalog;

        Pricebook2 internalPB = new Pricebook2(Name = 'Internal Listprices Quote', IsActive = true);
        insert internalPB;

        // Brand
        WebshopBrand__c brand = new WebshopBrand__c(
            Name = 'Lavazza',
            AssortmentExtensionEnabled__c = true
        );
        insert brand;

        // BuyerGroup
        BuyerGroup bg = new BuyerGroup(
            Name = 'Lavazza Coffee'
        );
        insert bg;

        // BuyerGroup
        BuyerGroup bg2 = new BuyerGroup(
            Name = 'Lavazza Sortimentserweiterung',
            Brand__c = brand.Id
        );
        insert bg2;

        // Account
        Account acct = new Account(
            Name = 'Test Account'
        );
        insert acct;

        BuyerAccount buyerAccount = new BuyerAccount(
            BuyerId = acct.Id,
            Name = 'Test Buyer Account',
            IsActive = true
        );
        insert buyerAccount;

        // Static BuyerGroupMember
        insert new BuyerGroupMember(
            BuyerGroupId = bg.Id,
            BuyerId = acct.Id,
            Dynamic__c = false
        );

        // WebStoreBuyerGroup

        insert new WebStoreBuyerGroup(
            BuyerGroupId = bg.Id,
            WebStoreId = webStore.Id
        );

        // Policy

        CommerceEntitlementPolicy policy =
            new CommerceEntitlementPolicy(
                Name='Policy'
            );
        insert policy;

        insert new CommerceEntitlementBuyerGroup(
            BuyerGroupId = bg.Id,
            PolicyId = policy.Id
        );

        Product2 product = new Product2(
            Name='Coffee Beans',
            IsActive=true,
            Tenant__c = '001',
            BrandWebshop__c = brand.Id
        );

        insert product;

        insert new CommerceEntitlementProduct(
            PolicyId = policy.Id,
            ProductId = product.Id
        );

        ProductCategory coffee =
            new ProductCategory(
                Name='KAFFEE',
                CatalogId = myCatalog.Id
            );

        insert coffee;

        insert new ProductCategoryProduct(
            ProductId = product.Id,
            ProductCategoryId = coffee.Id
        );
    }

    @IsTest
    static void testCreatesDynamicMembership() {

        Test.startTest();

        Database.executeBatch(
            new BatchAutomateBrandAssortmentExtension(),
            1
        );

        Test.stopTest();

        List<BuyerGroupMember> dynamicMembers = [

            SELECT BuyerId,
                   BuyerGroupId,
                   Dynamic__c

            FROM BuyerGroupMember

            WHERE Dynamic__c = TRUE
        ];

        System.assertEquals(
            1,
            dynamicMembers.size()
        );

        System.assert(dynamicMembers[0].Dynamic__c);
    }

    @IsTest
    static void testDisabledBrandProducesNothing() {

        WebshopBrand__c brand = [
            SELECT Id,
                   AssortmentExtensionEnabled__c
            FROM WebshopBrand__c
            LIMIT 1
        ];

        brand.AssortmentExtensionEnabled__c = false;
        update brand;

        Test.startTest();

        Database.executeBatch(
            new BatchAutomateBrandAssortmentExtension(),
            1
        );

        Test.stopTest();

        System.assertEquals(
            0,
            [SELECT COUNT()
             FROM BuyerGroupMember
             WHERE Dynamic__c = TRUE]
        );
    }

}