force-app/main/default/objects/AccountBrandAssignment__c/AccountBrandAssignment__c.object-meta.xml
<CustomObject>
    <label>Account Brand Assignment</label>
    <nameField>
        <displayFormat>ABA-{0000000}</displayFormat>
        <label>Account Brand Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Brand Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountBrandAssignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Brand Assignments</relationshipLabel>
    <relationshipName>AccountBrandAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBrandAssignment__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Brand has to be Assortment Extension Enabled.</errorMessage>
        <filterItems>
            <field>WebshopBrand__c.AssortmentExtensionEnabled__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>WebshopBrand__c</referenceTo>
    <relationshipLabel>Account Brand Assignments</relationshipLabel>
    <relationshipName>AccountBrandAssignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBrandAssignment__c/fields/UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>UniqueIdentifier__c</fullName>
    <label>Unique Identifier</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BuyerGroup/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>Buyer_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BuyerGroup/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CRM-1669</description>
    <label>Brand</label>
    <referenceTo>WebshopBrand__c</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>BuyerGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountBrandAssignmentHandler.cls
public without sharing class AccountBrandAssignmentHandler {
    public static void populateUniqueIdentifier(List<AccountBrandAssignment__c> newRecords){
        for(AccountBrandAssignment__c newRec : newRecords){
            newRec.UniqueIdentifier__c = newRec.Account__c + '' + newRec.Brand__c;
        }
    }
    public static void assignBuyerGroups(List<AccountBrandAssignment__c> newRecords){
        Set<Id> brandSet = new Set<Id>();
        Set<Id> accSet = new Set<Id>();
        for(AccountBrandAssignment__c newRec : newRecords){
            brandSet.add(newRec.Brand__c);
            accSet.add(newRec.Account__c);
        }
        Map<Id, Id> brandToBuyerGroupMap = new Map<Id, Id>();
        for(BuyerGroup bg : [SELECT Id, Brand__c FROM BuyerGroup WHERE Brand__c IN : brandSet]){
            brandToBuyerGroupMap.put(bg.Brand__c, bg.Id);
        }
        Set<Id> activeAccounts = new Set<Id>();
        for(BuyerAccount bacc : [SELECT Id, BuyerId FROM BuyerAccount WHERE BuyerId IN : accSet AND IsActive = TRUE]){
            activeAccounts.add(bacc.BuyerId);
        }
        List<BuyerGroupMember> bgmToInsert = new List<BuyerGroupMember>();
        for(AccountBrandAssignment__c newRec : newRecords){
            if(brandToBuyerGroupMap.containsKey(newRec.Brand__c) && activeAccounts.contains(newRec.Account__c)){
                bgmToInsert.add(new BuyerGroupMember(
                    BuyerId = newRec.Account__c,
                    BuyerGroupId = brandToBuyerGroupMap.get(newRec.Brand__c)
                ));
            }
        }
        if(!bgmToInsert.isEmpty()){
            Database.insert(bgmToInsert, false);
        }
    }
    public static void unassignBuyerGroups(List<AccountBrandAssignment__c> newRecords){
        Map<Id, Set<Id>> deletedRelationMap = new Map<Id, Set<Id>>();
        Set<Id> deletedBrandSet = new Set<Id>();
        for(AccountBrandAssignment__c newRec : newRecords){
            deletedBrandSet.add(newRec.Brand__c);
            Set<Id> innerSet = deletedRelationMap.containsKey(newRec.Account__c) ? deletedRelationMap.get(newRec.Account__c) : new Set<Id>();
            innerSet.add(newRec.Brand__c);
            deletedRelationMap.put(newRec.Account__c, innerSet);
        }
        List<BuyerGroupMember> bgmToDelete = new List<BuyerGroupMember>();
        for(BuyerGroupMember bgm : [SELECT Id, BuyerGroup.Brand__c, BuyerId FROM BuyerGroupMember WHERE BuyerId IN : deletedRelationMap.keySet() AND BuyerGroup.Brand__c IN : deletedBrandSet]){
            if(deletedRelationMap.containsKey(bgm.BuyerId) && deletedRelationMap.get(bgm.BuyerId).contains(bgm.BuyerGroup.Brand__c)){
                bgmToDelete.add(bgm);
            }
        }
        if(!bgmToDelete.isEmpty()){
            delete bgmToDelete;
        }
    }
}