force-app/main/default/objects/LeadConversionMapping__c/LeadConversionMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Lead Conversion Mapping</label>
</CustomObject>

force-app/main/default/objects/LeadConversionMapping__c/fields/Manual__c.field-meta.xml
<CustomField>
    <fullName>Manual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LeadConversionMapping__c/fields/SourceFieldName__c.field-meta.xml
<CustomField>
    <fullName>SourceFieldName__c</fullName>
    <label>Source Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadConversionMapping__c/fields/TargetFieldName__c.field-meta.xml
<CustomField>
    <fullName>TargetFieldName__c</fullName>
    <label>Target Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadConversionMapping__c/fields/TargetObjectName__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectName__c</fullName>
    <label>Target Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadConvertScheduleable.cls
/*
* Created by: Stanley Yin
* Created Date: 06-02-2024
* Purpose: Schedulable Class for B2BProductPriceCalculator Processing
*/

public class LeadConvertScheduleable implements Database.Batchable<SObject>,Database.AllowsCallouts,Schedulable{
    public static void execute(SchedulableContext sc) {
        Database.executeBatch(new LeadConvertScheduleable(), 1);
    }
    public Database.QueryLocator start(Database.BatchableContext bc){
        if(!Test.isRunningTest()){ delete [SELECT Id FROM LeadConversionMapping__c WHERE Manual__c = FALSE]; }  
        Id userId = UserInfo.getUserId();
        return Database.getQueryLocator('SELECT Id FROM User WHERE Id = : userID LIMIT 1');
    }
    public void execute(Database.BatchableContext bc,  List<User> scope){
        List<LeadConversionMapping__c> mappingsToInsert = new List<LeadConversionMapping__c>();
        MetadataService.MetadataPort service = new MetadataService.MetadataPort();
        service.SessionHeader = new MetadataService.SessionHeader_element();
        service.SessionHeader.sessionId = UserInfo.getSessionId();
        service.CallOptions = new MetadataService.CallOptions_element();
        service.timeout_x = 120000;

        List<MetadataService.LeadConvertSettings> leadConvertSettings = (List<MetadataService.LeadConvertSettings>) service.readMetadata('LeadConvertSettings', new List<String>{'LeadConvertSettings'}).getRecords();
        Integer i = 0;
        for (MetadataService.LeadConvertSettings leadConvertSetting : leadConvertSettings) {
            for (MetadataService.ObjectMapping objectMapping : leadConvertSetting.objectMapping) {
                for (MetadataService.ObjectMappingField fieldMapping : objectMapping.mappingFields) {
                    mappingsToInsert.add(new LeadConversionMapping__c(
                        Name = String.valueOf(i),
                        SourceFieldName__c = fieldMapping.inputField,
                        TargetFieldName__c = fieldMapping.outputField,
                        TargetObjectName__c = objectMapping.outputObject
                    ));
                    i++;
                }
            }
        }
        Database.insert(mappingsToInsert, false);
    }
    public void finish(Database.BatchableContext BC){ 
        // do nothing
    }
}